#!/usr/bin/env node
// Packman design tokens: XAML -> CSS.
//
// Packman is a WPF app; its design language lives in Packman/Themes/*.xaml
// (Color/Brush dictionaries, keyed Styles, icon geometries). This script is
// the deterministic bridge that design-sync (Claude Design) consumes: it
// reads those dictionaries and writes CSS custom properties + @font-face
// rules into .design-sync/pkg/ - the synthetic "packman-tokens" package the
// converter bundles. Nothing here is authored by hand: every value is read
// from the XAML, and the XAML key is kept in a trailing comment so the
// mapping back to the WPF resource is 1:1.
//
// Run: node .design-sync/gen-tokens.mjs   (from the repo root; re-run
// whenever Packman/Themes/*.xaml or Packman/Fonts/ change).
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const THEMES = join(ROOT, 'Packman', 'Themes');
const FONTS = join(ROOT, 'Packman', 'Fonts');
const OUT = join(HERE, 'pkg');
const PREFIX = 'pm';

const read = (f) => readFileSync(join(THEMES, f), 'utf8');
const kebab = (s) => s.replace(/([a-z])([A-Z0-9])/g, '$1-$2').replace(/([0-9])([A-Za-z])/g, '$1-$2').toLowerCase();
const tokenName = (key) => `--${PREFIX}-${kebab(key)}`;
const px = (n) => (Number(n) === 0 ? '0' : `${Number(n)}px`);

// ---------------------------------------------------------------- colours
// WPF colours are #AARRGGBB (or #RRGGBB). CSS wants rgb(r g b / a).
function cssColor(hex) {
  const h = hex.replace('#', '').toUpperCase();
  if (h.length === 6) return `#${h}`;
  const a = parseInt(h.slice(0, 2), 16) / 255;
  const r = parseInt(h.slice(2, 4), 16), g = parseInt(h.slice(4, 6), 16), b = parseInt(h.slice(6, 8), 16);
  if (a === 0) return 'transparent';
  if (a === 1) return `#${h.slice(2)}`;
  return `rgb(${r} ${g} ${b} / ${Number(a.toFixed(3))})`;
}
function parseTheme(file) {
  const xml = read(file);
  const colors = [];
  for (const m of xml.matchAll(/<Color x:Key="(\w+)Color">(#[0-9A-Fa-f]{6,8})<\/Color>/g)) colors.push([m[1], m[2]]);
  // Brush aliases whose key differs from their colour (e.g. LogoGradientBrush -> PrimaryColor).
  const aliases = [];
  for (const m of xml.matchAll(/<SolidColorBrush x:Key="(\w+)Brush" Color="\{StaticResource (\w+)Color\}"\/>/g)) {
    if (m[1] !== m[2]) aliases.push([m[1], m[2]]);
  }
  const isDark = /x:Key="IsDarkTheme">True</.test(xml);
  return { colors, aliases, isDark };
}
const dark = parseTheme('DarkTheme.xaml');
const light = parseTheme('LightTheme.xaml');
const darkKeys = dark.colors.map(([k]) => k), lightKeys = light.colors.map(([k]) => k);
const missing = [...darkKeys.filter((k) => !lightKeys.includes(k)), ...lightKeys.filter((k) => !darkKeys.includes(k))];
if (missing.length) throw new Error(`theme key mismatch between Dark and Light: ${missing.join(', ')}`);

function colorBlock(selector, theme, note) {
  const w = Math.max(...theme.colors.map(([k]) => tokenName(k).length)) + 1;
  const lines = theme.colors.map(([k, v]) => `  ${(tokenName(k) + ':').padEnd(w)} ${cssColor(v)};`.padEnd(w + 30) + ` /* ${k}Color */`);
  const al = theme.aliases.map(([b, c]) => `  ${(tokenName(b) + ':').padEnd(w)} var(${tokenName(c)});`.padEnd(w + 30) + ` /* ${b}Brush */`);
  return `/* ${note} */\n${selector} {\n  color-scheme: ${theme.isDark ? 'dark' : 'light'};\n${lines.join('\n')}\n${al.join('\n')}\n}\n`;
}
const colorsCss = `/* Packman colour tokens - generated by .design-sync/gen-tokens.mjs from
 * Packman/Themes/DarkTheme.xaml and LightTheme.xaml. Do not edit by hand.
 *
 * Role names are the XAML keys minus the "Color" suffix (CardColor ->
 * --pm-card). Both themes define the same roles; the app starts in Dark
 * (App.xaml merges DarkTheme.xaml) and Settings can switch to Light or
 * System, so Dark is the :root default and Light is opt-in via
 * data-theme="light" on any ancestor. Surfaces are translucent white/black
 * layers over the window base (Mica in the app) - alpha is intentional.
 */
${colorBlock(':root,\n[data-theme="dark"]', dark, 'Dark - DarkTheme.xaml (the default theme)')}
${colorBlock('[data-theme="light"]', light, 'Light - LightTheme.xaml')}`;

// ---------------------------------------------------------------- styles
const stylesXml = read('Styles.xaml');
const FONT_KEY = { UIFontFamily: 'font-ui', MonoFontFamily: 'font-mono', LabelFontFamily: 'font-label' };
const fontFamilies = [];
for (const m of stylesXml.matchAll(/<FontFamily x:Key="(\w+)">([^<]+)<\/FontFamily>/g)) {
  const list = m[2].replace(/^pack:\/\/[^#]*#/, '').split(',').map((s) => s.trim()).filter(Boolean);
  const generic = /Mono/.test(m[1]) ? 'monospace' : 'sans-serif';
  fontFamilies.push({ key: m[1], token: `--${PREFIX}-${FONT_KEY[m[1]] ?? kebab(m[1])}`, stack: [...list.map((f) => `"${f}"`), ...(generic === 'sans-serif' ? ['system-ui'] : []), generic].join(', ') });
}
const WEIGHTS = { Thin: 100, ExtraLight: 200, UltraLight: 200, Light: 300, Normal: 400, Regular: 400, Medium: 500, SemiBold: 600, DemiBold: 600, Bold: 700, ExtraBold: 800, UltraBold: 800, Black: 900, Heavy: 900 };
const thickness = (v) => {
  const p = v.split(',').map(Number);
  if (p.length === 1) return px(p[0]);
  if (p.length === 2) return `${px(p[1])} ${px(p[0])}`;              // WPF "h,v" -> CSS "v h"
  const [l, t, r, b] = p; return `${px(t)} ${px(r)} ${px(b)} ${px(l)}`; // WPF "l,t,r,b" -> CSS "t r b l"
};
const radius = (v) => v.split(',').map((n) => px(n)).join(' '); // WPF tl,tr,br,bl == CSS order
function resourceValue(v) {
  const r = v.match(/^\{(?:Dynamic|Static)Resource (\w+)\}$/);
  if (!r) return v === 'Transparent' ? 'transparent' : v;
  const key = r[1];
  if (FONT_KEY[key]) return `var(--${PREFIX}-${FONT_KEY[key]})`;
  if (key.endsWith('Brush')) return `var(${tokenName(key.slice(0, -5))})`;
  return `var(${tokenName(key)})`;
}
const PROP_MAP = {
  FontFamily: ['family', resourceValue],
  FontSize: ['size', px],
  FontWeight: ['weight', (v) => String(WEIGHTS[v] ?? v)],
  Foreground: ['color', resourceValue],
  Background: ['bg', resourceValue],
  BorderBrush: ['border-color', resourceValue],
  BorderThickness: ['border-width', thickness],
  Padding: ['padding', thickness],
  MinHeight: ['min-height', px],
  Height: ['height', px],
  Width: ['width', px],
  MinWidth: ['min-width', px],
  LineHeight: ['line-height', px],
  Opacity: ['opacity', (v) => v],
  CornerRadius: ['radius', radius],
};
const styles = new Map();
for (const m of stylesXml.matchAll(/<Style x:Key="(\w+)"([^>]*)>([\s\S]*?)\n\s*<\/Style>/g)) {
  const [, key, attrs, body] = m;
  const target = attrs.match(/TargetType="\{x:Type (\w+)\}"/)?.[1] ?? '';
  const basedOn = attrs.match(/BasedOn="\{StaticResource (\w+)\}"/)?.[1];
  const props = new Map(basedOn && styles.has(basedOn) ? styles.get(basedOn).props : []);
  // Style-level setters (before any ControlTemplate).
  const head = body.split('<ControlTemplate')[0];
  for (const s of head.matchAll(/<Setter Property="(\w+)" Value="([^"]+)"\/>/g)) {
    if (PROP_MAP[s[1]]) props.set(s[1], s[2]);
  }
  // Template radius: the control's own chrome Border ("bd", else the one
  // bound to the template's Background/BorderBrush, else the first).
  if (!props.has('CornerRadius') && body.includes('<ControlTemplate')) {
    const borders = [...body.matchAll(/<Border\b([^>]*)>/g)].map((b) => b[1]);
    const withRadius = borders.filter((b) => /CornerRadius="/.test(b));
    const pick = withRadius.find((b) => /x:Name="bd"/.test(b))
      ?? withRadius.find((b) => /TemplateBinding (Background|BorderBrush)/.test(b))
      ?? withRadius[0];
    const r = pick?.match(/CornerRadius="([^"]+)"/)?.[1];
    if (r) props.set('CornerRadius', r);
  }
  // Focus ring: drawn as an adorner Rectangle, not a Border.
  const ring = body.match(/<Rectangle Margin="(-?[\d.]+)" RadiusX="([\d.]+)"[^>]*Stroke="\{DynamicResource (\w+)\}" StrokeThickness="([\d.]+)"/);
  const focus = ring ? { offset: px(-Number(ring[1])), radius: px(ring[2]), color: resourceValue(`{DynamicResource ${ring[3]}}`), width: px(ring[4]) } : null;
  styles.set(key, { key, target, basedOn, props, focus });
}
function styleTokens(s) {
  const out = [];
  if (s.focus) {
    out.push([`${tokenName(s.key)}-ring`, `${s.focus.width} solid ${s.focus.color}`, `${s.key}: keyboard-only, drawn outside the control`]);
    out.push([`${tokenName(s.key)}-offset`, s.focus.offset, `${s.key} Margin`]);
    out.push([`${tokenName(s.key)}-radius`, s.focus.radius, `${s.key} RadiusX/RadiusY`]);
    return out;
  }
  for (const [prop, raw] of s.props) {
    const [suffix, conv] = PROP_MAP[prop];
    out.push([`${tokenName(s.key)}-${suffix}`, conv(raw), `${s.key}.${prop}`]);
  }
  return out;
}
const renderTokens = (rows) => {
  const w = Math.max(...rows.map(([n]) => n.length)) + 1;
  return rows.map(([n, v, c]) => `  ${(n + ':').padEnd(w)} ${v};`.padEnd(w + 34) + ` /* ${c} */`).join('\n');
};
const textStyles = [...styles.values()].filter((s) => s.target === 'TextBlock' && s.props.size);
const controlStyles = [...styles.values()].filter((s) => s.target !== 'TextBlock' && (s.props.size || s.focus));

const typographyCss = `/* Packman typography tokens - generated by .design-sync/gen-tokens.mjs from
 * Packman/Themes/Styles.xaml. Do not edit by hand.
 *
 * Font stacks are the XAML FontFamily fallback lists verbatim: Segoe UI
 * Variable / Cascadia Mono when the OS has them (Windows), else the bundled
 * Instrument Sans / JetBrains Mono / Martian Mono (fonts/fonts.css).
 * Sizes are WPF device-independent pixels, which equal CSS px.
 */
:root {
${renderTokens(fontFamilies.map((f) => [f.token, f.stack, f.key]))}

  /* Text styles - one group per keyed TextBlock style in Styles.xaml. */
${textStyles.map((s) => renderTokens(styleTokens(s))).join('\n\n')}
}
`;
const componentsCss = `/* Packman control tokens - generated by .design-sync/gen-tokens.mjs from
 * Packman/Themes/Styles.xaml. Do not edit by hand.
 *
 * One group per keyed control style (Button, TextBox, RadioButton, Border).
 * These are recipes, not components: build the control with plain elements
 * and apply the group's tokens. A style that is BasedOn another repeats the
 * inherited values so each group is complete on its own.
 */
:root {
${controlStyles.map((s) => renderTokens(styleTokens(s))).join('\n\n')}
}
`;

// ---------------------------------------------------------------- fonts
const FAMILY = { InstrumentSans: 'Instrument Sans', JetBrainsMono: 'JetBrains Mono', MartianMono: 'Martian Mono' };
const FILE_WEIGHT = { Regular: 400, Medium: 500, SemiBold: 600, Bold: 700 };
const faces = readdirSync(FONTS).filter((f) => f.endsWith('.ttf')).sort().map((f) => {
  const [fam, w] = f.replace(/\.ttf$/, '').split('-');
  if (!FAMILY[fam] || !FILE_WEIGHT[w]) throw new Error(`unrecognised font file ${f}`);
  return `@font-face {\n  font-family: "${FAMILY[fam]}";\n  font-style: normal;\n  font-weight: ${FILE_WEIGHT[w]};\n  font-display: swap;\n  src: url(../../Packman/Fonts/${f}) format("truetype");\n}`;
});
const fontsCss = `/* Packman bundled fonts - generated by .design-sync/gen-tokens.mjs from
 * Packman/Fonts/ (SIL OFL 1.1, see Packman/Fonts/README.md). Static 400-700
 * instances, latin + latin-ext. design-sync copies the files into fonts/
 * and rewrites these urls. */
${faces.join('\n')}
`;

// ---------------------------------------------------------------- base css
const stylesCss = `/* Packman base stylesheet - generated by .design-sync/gen-tokens.mjs.
 * Tokens live in tokens/*.css; this file only puts the app's default
 * surface, ink and typeface on the page so a design starts on-brand. */
body {
  margin: 0;
  background: var(--${PREFIX}-bg);
  color: var(--${PREFIX}-text);
  font-family: var(--${PREFIX}-font-ui);
  -webkit-font-smoothing: antialiased;
}
code, kbd, pre, samp {
  font-family: var(--${PREFIX}-font-mono);
}
`;

// ---------------------------------------------------------------- icons
const iconsXml = read('Icons.xaml');
const icons = [...iconsXml.matchAll(/<PathGeometry x:Key="Icon(\w+)" Figures="([^"]+)"\/>/g)].map((m) => [m[1], m[2].replace(/\s+/g, ' ').trim()]);
const iconsMd = `---
category: Icons
---
# Packman icons

Generated by \`.design-sync/gen-tokens.mjs\` from \`Packman/Themes/Icons.xaml\`. Do not edit by hand.

${icons.length} stroke icons on a 24 x 24 viewbox. In the app they are drawn as a \`Path\` with a
1.5 to 2.4 px stroke (1.8 to 2 is typical), round caps and joins, no fill, in the current text
colour. Reproduce one as inline SVG:

\`\`\`html
<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor"
     stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
  <path d="${icons.find(([n]) => n === 'Folder')?.[1] ?? icons[0][1]}"/>
</svg>
\`\`\`

| Name | Path data (\`d\`) |
|---|---|
${icons.map(([n, d]) => `| \`Icon${n}\` | \`${d}\` |`).join('\n')}
`;

// ---------------------------------------------------------------- write
mkdirSync(join(OUT, 'tokens'), { recursive: true });
mkdirSync(join(OUT, 'docs'), { recursive: true });
const files = {
  'tokens/colors.css': colorsCss,
  'tokens/typography.css': typographyCss,
  'tokens/components.css': componentsCss,
  'fonts.css': fontsCss,
  'styles.css': stylesCss,
  'docs/icons.md': iconsMd,
};
for (const [rel, text] of Object.entries(files)) writeFileSync(join(OUT, rel), text);
console.error(`gen-tokens: ${dark.colors.length} colour roles x 2 themes, ${fontFamilies.length} font stacks, ${textStyles.length} text styles, ${controlStyles.length} control styles, ${faces.length} font faces, ${icons.length} icons -> ${OUT}`);
